proxy:
  replicaCount: 1

  image:
    repository: oven/bun
    tag: "1.3"
    pullPolicy: IfNotPresent

  port: 8080
  grokBaseUrl: "https://api.x.ai/v1"
  chatBaseUrl: "https://api.deepseek.com"

  resources:
    requests:
      cpu: 50m
      memory: 100Mi
    limits:
      memory: 100Mi

  ingress:
    enabled: false
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod
    hosts:
      - grokproxy.MYDOMAIN.com
    tls:
      enabled: true
